const asyncHandler = require('express-async-handler');
const { Parser } = require('json2csv');
const PDFDocument = require('pdfkit');
const Certification = require('../models/Certification.js');

/**
 * @desc    Export user certifications in JSON, CSV, or PDF
 * @route   GET /api/certifications/export?format=json|csv|pdf
 * @access  Private
 */
const exportCertifications = asyncHandler(async (req, res) => {
  const format = (req.query.format || 'json').toLowerCase();
  const certifications = await Certification.find({ userId: req.user.id });

  if (certifications.length === 0) {
    res.status(404);
    throw new Error('No certifications found to export');
  }

  // ── JSON Export ──
  if (format === 'json') {
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', 'attachment; filename="certifications.json"');
    return res.status(200).json({ success: true, count: certifications.length, data: certifications });
  }

  // ── CSV Export ──
  if (format === 'csv') {
    const fields = [
      { label: 'Title', value: 'title' },
      { label: 'Provider', value: 'provider' },
      { label: 'Exam Date', value: (row) => row.examDate ? new Date(row.examDate).toLocaleDateString() : 'N/A' },
      { label: 'Progress (%)', value: 'progress' },
      { label: 'Milestones', value: (row) => row.milestones.map(m => `${m.title} [${m.completed ? '✓' : '✗'}]`).join('; ') },
      { label: 'Completed Topics', value: (row) => row.completedTopics.join('; ') },
    ];

    const parser = new Parser({ fields });
    const csv = parser.parse(certifications);

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename="certifications.csv"');
    return res.status(200).send(csv);
  }

  // ── PDF Export ──
  if (format === 'pdf') {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="certifications.pdf"');
    doc.pipe(res);

    // Title page header
    doc.fontSize(22).font('Helvetica-Bold').text('Certification Tracker Report', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#6b7280')
      .text(`Generated on ${new Date().toLocaleDateString()} • ${certifications.length} certification(s)`, { align: 'center' });
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(1);

    // Loop through each certification
    certifications.forEach((cert, index) => {
      // Add new page if not enough space
      if (doc.y > 650) doc.addPage();

      // Cert number + title
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827')
        .text(`${index + 1}. ${cert.title}`);
      doc.moveDown(0.3);

      // Provider & Exam Date
      doc.fontSize(10).font('Helvetica').fillColor('#374151')
        .text(`Provider: ${cert.provider}`, { continued: true })
        .text(`    |    Exam Date: ${cert.examDate ? new Date(cert.examDate).toLocaleDateString() : 'Not set'}`, { continued: true })
        .text(`    |    Progress: ${cert.progress}%`);
      doc.moveDown(0.5);

      // Progress bar
      const barX = 50, barY = doc.y, barW = 200, barH = 10;
      doc.roundedRect(barX, barY, barW, barH, 3).fillColor('#e5e7eb').fill();
      if (cert.progress > 0) {
        const fillW = (cert.progress / 100) * barW;
        doc.roundedRect(barX, barY, fillW, barH, 3).fillColor(cert.progress === 100 ? '#22c55e' : '#6366f1').fill();
      }
      doc.moveDown(1.2);

      // Milestones
      if (cert.milestones.length > 0) {
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#111827').text('Milestones:');
        cert.milestones.forEach((m) => {
          const icon = m.completed ? '✓' : '○';
          const color = m.completed ? '#22c55e' : '#6b7280';
          doc.fontSize(9).font('Helvetica').fillColor(color).text(`  ${icon}  ${m.title}`);
        });
        doc.moveDown(0.5);
      }

      // Completed Topics
      if (cert.completedTopics.length > 0) {
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#111827').text('Completed Topics:');
        doc.fontSize(9).font('Helvetica').fillColor('#374151')
          .text(`  ${cert.completedTopics.join('  •  ')}`);
        doc.moveDown(0.5);
      }

      // Separator
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
      doc.moveDown(0.8);
    });

    // Footer
    doc.fontSize(8).font('Helvetica').fillColor('#9ca3af')
      .text('Generated by CertTracker', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
    return;
  }

  // Invalid format
  res.status(400);
  throw new Error('Invalid format. Use json, csv, or pdf.');
});

module.exports = { exportCertifications };
